version: "3.9"
services:
  tracer:
    image: "jaegertracing/all-in-one"
    environment: 
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  db:
    image: "mysql"
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
       - db-data:/var/lib/mysql
       - ./docker/my.cnf:/etc/mysql/my.cnf
    environment: 
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"

  db-ui:
    image: "adminer"
    ports: 
      - 8282:8080

  redis:
    image: "redis"
    volumes:
       - redis-data:/data
    ports:
      - "6379:6379"
  locust-master:
    image: "locustio/locust"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master -H http://docker.for.mac.localhost:8080
    ports:
      - "8089:8089"
  locust-worker:
    image: "locustio/locust"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus


volumes:
  db-data:
  redis-data:
  locust-data:
  grafana-storage:
  prometheus_data:
