// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire gen -tags "dynamic"
//+build !wireinject

package main

import (
	"context"
	"factory/exam/config"
	"factory/exam/handler"
	"factory/exam/infra"
	"factory/exam/repo/mysql"
	"factory/exam/server"
	"factory/exam/server/kafka"
	"factory/exam/services"
)

// Injectors from buildServer.go:

func buildServer(ctx context.Context) (*server.Manager, error) {
	configuration := infra.InitConfiguration()
	connPool, err := infra.GetConnectionPool(configuration)
	if err != nil {
		return nil, err
	}
	productMySQLRepo := mysql.NewProductMySQLRepo(connPool)
	productService := services.ProductProvider(productMySQLRepo)
	productHandler := handler.ProductHandlerProvider(productService)
	productPBHandler := handler.NewProductPBHandler(productService)
	httpServer, err := server.HTTPProvider(ctx, productHandler, productPBHandler)
	if err != nil {
		return nil, err
	}
	metricPort := config.ProvideMetricPort()
	metricServer, err := server.NewMetricServer(metricPort)
	if err != nil {
		return nil, err
	}
	kafkaConsumer, err := kafka.NewKafkaConsumer()
	if err != nil {
		return nil, err
	}
	kafkaProducer, err := kafka.NewKafkaProducer()
	if err != nil {
		return nil, err
	}
	manager := server.NewServerManager(httpServer, metricServer, kafkaConsumer, kafkaProducer)
	return manager, nil
}
